title:              UJC-USP
description:        União da Juventude Comunista
author:             UJC-USP
baseurl:            "/"
url:                "https://ujc-usp.github.io"

# Social Profiles
twitter_username:   
github_username:    UJC-USP
facebook_username:  "UJC.USP"
instagram_username: "ujc.usp"
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/boletim/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
